config/routes.rb
Rails.application.routes.draw do
  get '/', to: "home#top"
  get 'about', to: "home#about"
  resources :blogs do
  collection do
    post :confirm
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true
    validates :content,length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "test"
    else
      render 'new'
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "test2"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blog_params)
     render :new if @blog.invalid?
  end
  
  private
  def blog_params
    params.require(:blog).permit(:content)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/confirm.html.erb
<div class="text-center">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <h3>CONTENT:<%= @blog.content %></h3>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class="text-center">
<%= form_with(model: @blog, local: true) do |form| %>  

<% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="blog_title">
        <h3>
            <%= form.label  :content %>
        </h3>
        <%= form.text_area :content, size: "50x12" %>
    </div>
    <%= form.submit "Tweet" %>
<% end %>
</div>

app/views/blogs/index.html.erb
<div class="text-center">
<% @blogs.each do |blog| %>
    <div class="blogs-index">
        <%= link_to blog.content, blog_path(blog.id) %>
      </div>
<% end %>
</table>
<br>
</div>

app/views/blogs/new.html.erb
<div class="text-center">
<%= form_with(model: @blog, local: true ,url: confirm_blogs_path ) do |form| %>


<% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
   <div class="blog_title">
    <h3>
        <%= form.label  :content %>
    </h3>
    <%= form.text_area :content, size: "50x12" %>
  </div>
  <%= form.submit "Tweet", size: "50x12" %>
<% end %>
</div>

app/views/blogs/show.html.erb
<div class="text-center main posts-show">
    <div class="posts-show-item" >
    <h1>
        Content
    </h1>
    <h3>
        <%= @blog.content %>
    </h3>
    <h1>
        Created_at
    </h1>
    <h3>
        <%= @blog.created_at %>
    </h3>
    <div>
        <div class="btn btn-default btn-lg">
            <%= link_to "EDIT", edit_blog_path(@blog.id) %>
        </div>
        <div class="btn btn-default btn-lg">
            <%= link_to 'DELETE', blog_path(@blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
        </div>
    </div>
    </div>
</div>

app/views/home/about.html.erb
<div class="text-center row" id="green">
    <div class="col-lg-8 col-lg-offset-2 centered">
                    <h1>WHAT WE CAN DO?</h1>
                    <h2>Hear what people are talking about.</h2>
                    <h2>Join the conversation.</h2>
                    <p>Tweets, which may include hyperlinks, are limited to 140 characters,
                    due to the constraints of Twitter's Short Message Service (SMS) delivery system. 
                    Because tweets can be delivered to followers in real time,
                    they might seem like instant messages to the novice user. </p>
                    <div class ="jumbotron" style ="height:450px; color:white;
                    background:url(/assets/news.jpg);  background-size:cover;">
    </div><!-- /col-lg-8 -->
</div>

app/views/home/top.html.erb
<div id="hello">
<div class="text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 centered">
            <h1>Tweetexam</h1>
            <h2>See what’s happening in the world right now</h2>
            <div class ="jumbotron" style ="height:300px; color:white;
            background:url(/assets/smartphone-1445489_960_720.jpg);  background-size:cover;">
            </div>
        </div><!-- /col-lg-8 -->
    </div><!-- /row -->
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetexam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"> 
    <nav class="navbar navbar-default" style="background-color: #D8D8D8;">
      <div class="container-fluid">
        <ul class="nav navbar-nav home-bar">
          <li>
            <a href="/"><span class="glyphicon glyphicon-home"></span> HOME</a>
          </li>
          <li>
            <a href="/blogs/new"><span class="glyphicon glyphicon-pencil"></span> NEW_BLOG</a>
          </li>
          <li>
            <a href="/blogs"><span class="glyphicon glyphicon-folder-close"></span> INDEX</a>
          </li>
          <li>
            <a href="/about"><span></span> ABOUT</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
    </div> 
    <footer class=" text-center" style="color:blue;">
    <p>Phase3_Bootstrap  2018 Dive_Into_Code_Student.</p>
  </footer>
  </body>
</html>